### ISSUE TITLE
[bug] failed test when `cargo test -- --test-threads=1` execute

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa#1170]
**Describe the bug**
failed test when `cargo test -- --test-threads=1` execute

successed test when `RUST_TEST_THREADS=1 cargo test`  exevute

**Comment by hitenkoku** [comment]
```
> cargo test -- -test-threads=1
...
failures:
    tests::test_exec_general_html_output
    tests::test_exec_none_storedstatic
    tests::test_overwrite_csv
    tests::test_overwrite_json
    tests::test_same_file_output_computer_metrics_csv
    tests::test_same_file_output_computer_metrics_exit
    tests::test_same_file_output_csv_exit
    tests::test_same_file_output_json_exit
    tests::test_same_file_output_logon_summary_csv
    tests::test_same_file_output_logon_summary_csv_exit
    tests::test_same_file_output_metric_csv
    tests::test_same_file_output_metric_csv_exit

---- tests::test_exec_general_html_output stdout ----
thread 'tests::test_exec_general_html_output' panicked at 'Command csv-timeline: Argument or group 'exclude-category' specified in 'conflicts_with*' for 'include_category' does not exist', 
...
```

**Comment by hitenkoku** [comment]
The error was due to the fact that the variable specified in conflict_with was not yet defined.

When the error was corrected, `-test-threads` was recognised as a hayabusa option when executed, resulting in an error.

I think that cargo test `-- -test-threads=1` can also be supported if `-test-threads` is registered as a debugging option as a way

**Comment by YamatoSecurity** [comment]
I see, thanks for looking into this!

**Comment by Shirofune-Security** [comment]
This is still reproducible on current `main`. The original `exclude-category` `conflicts_with` panic is fixed, but the remaining cause is `App::check_is_valid_args_num` in `src/main.rs`, which detects "subcommand run with no arguments" from the **global process arg count**:

```rust
Action::CsvTimeline(_) | ... | Action::ComputerMetrics(_) => env::args().len() != 2,
```

When the count is "invalid" the caller prints the subcommand help and returns early. Under `cargo test`, `env::args()` is the **test harness's** argv, not hayabusa's:

| Invocation | `env::args()` | `len() != 2` | Result |
| --- | --- | --- | --- |
| `cargo test` | `[binary]` | true → valid | ✅ pass |
| `RUST_TEST_THREADS=1 cargo test` | `[binary]` | true → valid | ✅ pass |
| `cargo test -- --test-threads=1` | `[binary, --test-threads=1]` | **false → "no args"** | ❌ help printed, early return, no output |

That's why every failing test maps to an action listed in `check_is_valid_args_num` (`test_same_file_output_*`, `test_overwrite_*`, `test_exec_general_html_output`, …), and why the env-var form (`RUST_TEST_THREADS=1`, not an argv) always worked. The same heuristic also breaks running a single test by name (e.g. `cargo test test_overwrite_csv` — also two args).

Opened a fix in #1796 — it skips the heuristic in test builds (`cfg!(test)`), where `env::args()` is meaningless; the shipped binary is unaffected.

**Comment by Shirofune-Security** [comment]
⚠️ Heads-up: this issue was auto-closed by merging #1796, but the bug is **not actually fixed yet** — it may be worth reopening.

I pulled the merge commit (`f5dadb7b`) and `cargo test -- --test-threads=1` still fails identically:

```
test tests::test_exec_general_html_output ... error: unexpected argument '--test-threads' found
  process didn't exit successfully: `target/debug/deps/hayabusa-<hash> --test-threads=1` (exit status: 2)
```

**Corrected root cause:** my earlier analysis pinned this on `check_is_valid_args_num`, which #1796 guarded — but that function only counts `env::args()` and returns a `bool`, so it can't produce clap's `unexpected argument` error. The real abort is in **`ConfigReader::new()` (`src/detections/configs.rs`)**, which calls `Config::parse()`. That reads `std::env::args()`, sees the test harness's own flags (`--test-threads=1`, test-name filters, …), and clap hard-exits the whole process before any assertion runs. `cfg!(test)` can't guard it because the binary's tests link the library compiled *without* the test cfg.

I opened **#1797** with the missing piece: `Config::try_parse()` + a runtime check for the `target/.../deps/` test binary, falling back to a default config there (real runs still error out normally).

Verified locally — both fixes are needed together:

| branch | `cargo test -- --test-threads=1` |
|---|---|
| merged main `f5dadb7b` (after #1796) | ❌ aborts at `test_exec_general_html_output`, exit 2 |
| merged main + #1797 | ✅ `423 passed` + `17 passed`, exit 0 |
